feat: added frontend code of video-lib
Jaynil1611/Dietify-Diaries pull request #1
Opened 2021-05-05 13:58 UTC by Jaynil1611

- [Dietify Diaries Live](https://dietify-diaries.vercel.app/)

2021-05-06 06:22 UTC, vinaybajjuri58 requested changes
Hey Jaynil 
UI of the application looks good. Here some of the suggestions from my side :
->Add a toast or snackbar to display about the action performed 
->Try changing title while user is navigating between pages 
->Also add navlink active class css

2021-05-06 06:22 UTC, vinaybajjuri58 commented on src/reducers/videoReducer.js
> +        dislikedVideos: removeVideo(prevState.dislikedVideos, payload.id),
passing arguments in an object would be better ,so that we need not to follow any sequence while using them in function

2021-05-06 06:22 UTC, vinaybajjuri58 commented on src/App.jsx
> +        </div>
This code can be moved to a seperate component like RoutesComponent later if you want to add a new route it would be easy,Just a suggestion.

2021-05-06 09:54 UTC, sjsouvik requested changes
- since you've added toast related states in context, toast for one for page will be visible in another page as well, if you visit quickly
- add 404 not found page
- try to keep one component in each jsx file, it'll look cleaner
- remove commented code once the feature implementation is done

2021-05-08 18:21 UTC, Aravindan07 requested changes
Hey, Jaynil great work with the video library. I have some suggestions/changes to make it more accessible and neat.
1. Add active state to sidebar menu items. For. eg if the user clicks on liked videos page from the sidebar highlight that link in order to denote the user that he's on the liked videos page.
2.  Modal width feels too large, try reducing it to 50%. 
3.  Add a toast message whenever a user performs an action, like saving it to liked videos, etc.,
4.  I am able to create a playlist with no name. If you didn't do it intentionally fix it.
5. Change the cursor to pointer in playlists and liked videos, X icon and in delete icon.
6. Vinay and Souvik had already suggested most of the changes needed, Hence I am adding only few.

2021-05-08 18:21 UTC, Aravindan07 commented on src/index.js
> +// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
remove these unwanted comments jaynil

2021-05-08 18:21 UTC, Aravindan07 commented on src/contexts/videoContext.js
> +    toastMessage: "",
Move this initial state into a separate variable and consume it. So that if this initial state is required by other contexts it can be reused.

2021-05-08 18:21 UTC, Aravindan07 commented on src/components/Video/Video.jsx
> +        <VideoListing videoList={taggedData} />
Components like Searchbar, Tags, and VideoListing are consumed first in the file and then it is defined. Although this doesn't cause any error it is always good to define first and consume it.

2021-05-08 18:21 UTC, Aravindan07 commented on src/components/Video/VideoDetail/VideoDetail.jsx
> +
Try to define this component in a separate file and consume it, it will reduce the lines written in this file and also becomes more readable.

2021-05-09 08:21 UTC, Jaynil1611 commented on src/reducers/videoReducer.js
> +        dislikedVideos: removeVideo(prevState.dislikedVideos, payload.id),
Actually, I am reusing these functions for many lists in the context, so in the arguments of these functions accept any list and corresponding payload and return an updated list. So, passing objects will not allow a generic list argument,
e.g
```javascript
const addVideo = (list, video) => {
  return list.concat(video);
};```

2021-05-09 09:55 UTC, Jaynil1611 commented on src/database/database.js
> +  //     getVideoURL(id)
Actually, I have kept it for backend reference. I will remove it once I integrate backend into the app.

2021-05-09 10:26 UTC, Jaynil1611 commented on src/components/Video/Video.jsx
> +        <VideoListing videoList={taggedData} />
Yeah, I kept it at the last to allow the reader to focus on the main component in the file and keep repeating components separately

2021-05-09 10:33 UTC, Jaynil1611 commented on src/App.jsx
> +        </div>
Done

2021-05-09 10:33 UTC, Jaynil1611 commented on src/App.jsx
> +          </Routes>
Done

2021-05-09 10:33 UTC, Jaynil1611 commented on src/components/Playlists/PlayLists.jsx
> +            src={videoList[0].thumbnailUrl}
Done

2021-05-09 10:33 UTC, Jaynil1611 commented on src/index.js
> +// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
Done

2021-05-09 10:33 UTC, Jaynil1611 commented on src/contexts/videoContext.js
> +    toastMessage: "",
Done

2021-05-09 17:24 UTC, Jaynil1611 commented on src/components/Video/VideoDetail/VideoDetail.jsx
> +
Done

2021-05-09 17:28 UTC, Aravindan07 approved these changes

2021-05-09 17:29 UTC, vinaybajjuri58 commented on src/reducers/videoReducer.js
> +        dislikedVideos: removeVideo(prevState.dislikedVideos, payload.id),
Yeah I got what you are saying 
But what I meant was if you are adding a video to history 
```addVideo({list:history, video:video})```
for liked ```addVideo({list:likedVideos,video:video})```

2021-05-09 17:29 UTC, Aravindan07 commented
I can see the changes in the code as well as in the app so I am approving this review!

2021-05-09 17:31 UTC, vinaybajjuri58 approved these changes
Approving all the changes suggested by me. Good Job! @Jaynil1611

2021-05-10 02:24 UTC, sjsouvik commented
Approve all the changes that are requested by me.

2021-05-14 13:15 UTC, sjsouvik approved these changes

2021-05-14 13:16 UTC, sjsouvik approved these changes

2021-06-04 17:31 UTC, khusharth commented
- You can use fixed height for the video tittle to so that every card is of same height!
- Use proper alerts for errors / validation i.e something with an warning sign / red color.

2021-06-04 17:54 UTC, khusharth commented on frontend/src/App.jsx
> +            <ul className="list__group li--border sidebar--scroll">
Can create a sidebar component for this.

2021-06-11 15:50 UTC, vinaybajjuri58 reviewed
Hey Jaynil 
Everything in authentication implementation part looks fine
I liked the way you implemented validation in schema

2022-08-29 18:19 UTC, merged