feat: added backend integration to video-library frontend
Jaynil1611/Dietify-Diaries pull request #4
Opened 2021-05-20 08:22 UTC by Jaynil1611

- [https://dietify-diaries.vercel.app/](Frontend Live)
- [https://dietify-diaries-backend.herokuapp.com/](Backend Live)

2021-05-23 05:27 UTC, Aravindan07 commented on backend/index.js
> +// userId: 60a35a72ffb1fa01498940eb
Remove logs which are unneccesary

2021-05-23 06:51 UTC, Aravindan07 requested changes
Great work Jaynil, Your code looks really clean.

If i like a video it is added to liked videos then if I dislike a video it is removed from the liked videos, then again if I click on the like button it is not adding it to liked videos and the server is giving me a 400 error. If it is an issue in backend fix it

2021-05-23 06:51 UTC, Aravindan07 commented on backend/models/savedVideo.model.js
> +module.exports = { SavedVideo };
These two lines can be wriiten in single line like 
` module.exports = mongoose.model("SavedVideo",SavedVIdeoSchema);`

2021-05-23 06:51 UTC, Aravindan07 commented on backend/controllers/historyLikeSave.controller.js
> +    videos = getNormalizedVideoList(videos);
If you want to normalize data then .select() would work. For example, if you want to remove the __v from data then use `.select("-__v)`. The - operator indicates that remove __v from the data. So you can neglect the use of another function.

2021-05-23 06:51 UTC, Aravindan07 commented on backend/controllers/historyLikeSave.controller.js
> +    let video = req.body;
I hope you are not changing the value of this variable, so use const instead of let.

2021-05-23 06:51 UTC, Aravindan07 commented on backend/controllers/historyLikeSave.controller.js
> +};
Is a delete operation not a DB operation. If so use try-catch block

2021-05-23 06:51 UTC, Aravindan07 commented on backend/controllers/playlist.controller.js
> +    updatedPlaylist = await playlist.save();
You haven't declared updatedPlaylist anywhere I hope. Use const or let

2021-05-23 06:51 UTC, Aravindan07 commented on backend/controllers/video.controller.js
> +    let videos = await Video.find({});
Use const if you are not changing the value

2021-05-23 06:51 UTC, Aravindan07 commented on backend/controllers/video.controller.js
> +  let { video } = req;
Use const instead

2021-05-23 06:51 UTC, Aravindan07 commented on backend/index.js
> +app.use(bodyParser.json());
You don't need to install bodyParser package separately. It is inbuilt in the express package. Use `app.use(express.json())` instead of `app.use(bodyParser.json())` .

2021-05-23 09:53 UTC, vinaybajjuri58 requested changes
Hey Jaynil, I have added some of the suggestions

2021-05-23 09:53 UTC, vinaybajjuri58 commented on backend/controllers/playlist.controller.js
> +  }
Does this code mean a user can have only one playlist?

2021-05-23 09:53 UTC, vinaybajjuri58 commented on backend/controllers/playlist.controller.js
> +
Wrap it in a try-catch block, so it will be easy in error handling

2021-05-23 09:53 UTC, vinaybajjuri58 commented on backend/index.js
> +})
this code can be separated out into files like pathNotfoundHandler, errorHandler

2021-05-23 09:53 UTC, vinaybajjuri58 commented on backend/middlewares/paramHandler.js
> +    if (!video) {
I'm curious about why you are using findOne, findById can also be used right?

2021-05-23 09:53 UTC, vinaybajjuri58 commented on backend/models/video.model.js
> +  favoriteCount: { type: String, required: true },
types of viewCount , likeCount , favoriteCount should be number I guess ?

2021-05-23 09:53 UTC, vinaybajjuri58 commented on backend/controllers/historyLikeSave.controller.js
> +    }
Since you are having, viewCount in the video model, So on adding a video to users history, view-count in the video model should also be incremented I guess

2021-05-24 11:28 UTC, Jaynil1611 commented on backend/models/savedVideo.model.js
> +module.exports = { SavedVideo };
it's okay to use an extra variable here to define the model

2021-05-24 11:32 UTC, Jaynil1611 commented on backend/controllers/historyLikeSave.controller.js
> +    videos = getNormalizedVideoList(videos);
I need to discuss more on this one, didn't get you.

2021-05-24 11:37 UTC, Jaynil1611 commented on backend/models/video.data.js
> +          "healthy food channel",
Done

2021-05-24 11:37 UTC, Jaynil1611 commented on backend/index.js
> +// userId: 60a35a72ffb1fa01498940eb
Done

2021-05-24 11:38 UTC, Jaynil1611 commented on backend/controllers/historyLikeSave.controller.js
> +    let video = req.body;
Done

2021-05-24 11:38 UTC, Jaynil1611 commented on backend/controllers/historyLikeSave.controller.js
> +};
Done

2021-05-24 11:38 UTC, Jaynil1611 commented on backend/controllers/playlist.controller.js
> +    updatedPlaylist = await playlist.save();
Done

2021-05-24 11:39 UTC, Jaynil1611 commented on backend/controllers/video.controller.js
> +    let videos = await Video.find({});
Done

2021-05-24 11:40 UTC, Jaynil1611 commented on backend/controllers/video.controller.js
> +  let { video } = req;
Done

2021-05-24 11:40 UTC, Jaynil1611 commented on backend/index.js
> +app.use(bodyParser.json());
Done

2021-05-24 11:42 UTC, Jaynil1611 commented on backend/controllers/playlist.controller.js
> +  }
The user can have only one playlist with `one name`, the user cannot have multiple playlists with same `name`

2021-05-24 11:43 UTC, Jaynil1611 commented on backend/controllers/playlist.controller.js
> +
Done

2021-05-24 11:49 UTC, Jaynil1611 commented on backend/index.js
> +})
Done

2021-05-24 11:53 UTC, Jaynil1611 commented on backend/middlewares/paramHandler.js
> +    if (!video) {
Changed it to findById

2021-05-24 11:54 UTC, Jaynil1611 commented on backend/models/video.model.js
> +  favoriteCount: { type: String, required: true },
Actually, I have followed the Youtube API format where they have all three in string format

2021-05-24 11:59 UTC, Jaynil1611 commented on backend/controllers/historyLikeSave.controller.js
> +    }
Yeah, but I am not showing viewCount anywhere as of now, I will add it afterwards

2021-05-24 14:12 UTC, Aravindan07 commented on backend/models/savedVideo.model.js
> +module.exports = { SavedVideo };
Ok not a problem

2021-05-24 15:13 UTC, Aravindan07 commented on backend/index.js
> +app.use(bodyParser.json());
You haven't uninstalled bodyParser package please do that

2021-05-24 15:13 UTC, Aravindan07 approved these changes

2021-05-24 17:05 UTC, vinaybajjuri58 approved these changes

2022-08-29 18:19 UTC, merged